sonar.projectKey=devsecops-jenkins-pipeline
sonar.projectName=DevSecOps Jenkins Pipeline
sonar.sources=app
sonar.tests=app
sonar.test.inclusions=app/test_*.py
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
